CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(45) NOT NULL,
  password VARCHAR(255) NOT NULL,
  enabled INT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS authorities (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(45) NULL,
    authority VARCHAR(45) NULL
    );